---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Template to create WorkStation EC2 Server'

Parameters:
  CFNServiceRoleArn:
    Description: Importing CFNServiceRoleArn from Parent EKS Infrastructure template
    Type: String
  
  EKSMaster:
    Description: Importing EKSMaster from Parent EKS Infrastructure template
    Type: String
  
  NodeInstanceRoleArn:
    Description: Importing NodeInstanceRoleArn from Parent EKS Infrastructure template
    Type: String

  VpcId:
    Description: Importing VpcId from Parent EKS Infrastructure template
    Type: String

  SSHCidr:
    Description: Importing SSHCidr from Parent EKS Infrastructure template
    Type: String

  WorkStationSubnet:
    Description: Importing WorkStationSubnet from Parent EKS Infrastructure template
    Type: String

  KeyName:
    Description: Importing KeyName from Parent EKS Infrastructure template
    Type: String

  NodeImageId:
    Description: Importing NodeImageId from Parent EKS Infrastructure template
    Type: String

  CFNServiceRole:
    Description: Importing CFNServiceRole from Parent EKS Infrastructure template
    Type: String

  KubectlBinarylink:
    Description: Importing KubectlBinarylink from Parent EKS Infrastructure template
    Type: String
  
  AwsIamAuthenticatorBinaryLink:
    Description: Importing AwsIamAuthenticatorBinaryLink from Parent EKS Infrastructure template
    Type: String
  
  k8sDashboardlink:
    Description: Importing k8sDashboardlink from Parent EKS Infrastructure template
    Type: String

Resources:
  WorkStationInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref WorkStationInstanceRole

  WorkStationInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole

  WorkStationIAMPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub 'WorkStationIAMPolicy-${EKSMaster}'
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          -
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: !Ref CFNServiceRoleArn
          -
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: !GetAtt ExtraInstanceRole.Arn
      Roles: 
        - 
          Ref: "WorkStationInstanceRole"

  WorkStationIAMPolicy2:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub 'WorkStationIAMPolicy02-${EKSMaster}'
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          -
            Effect: "Allow"
            Action: 
              - "iam:PassRole"
              - "eks:DescribeCluster"
              - "iam:Update*"
              - "iam:List*"
              - "sts:AssumeRole"
            Resource: "*"
      Roles: 
        - 
          Ref: "WorkStationInstanceRole"

  ExtraInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref ExtraInstanceRole

  ExtraInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
            - sts:AssumeRole
          -
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt WorkStationInstanceRole.Arn
            Action:
            - sts:AssumeRole

  ExtraIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'ExtraIAMPolicy-${EKSMaster}'
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          -
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: !Ref CFNServiceRoleArn           
      Roles: 
        - 
          Ref: "ExtraInstanceRole"

  WorkStationSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
        GroupDescription: This security group will be associated with WorkStation Instance.
        VpcId:
            Ref: VpcId
        SecurityGroupIngress:
            - 
                IpProtocol: tcp
                FromPort: '1025'
                ToPort: '65535'
                CidrIp: 0.0.0.0/0
            - 
                IpProtocol: tcp
                FromPort: '22'
                ToPort: '22'
                CidrIp:
                    Ref: SSHCidr
                    
  WorkStation:
    Type: 'AWS::EC2::Instance'
    Properties:
      IamInstanceProfile: !Ref WorkStationInstanceProfile
      ImageId: !Ref NodeImageId
      InstanceType: "t2.medium"
      SubnetId: !Ref WorkStationSubnet
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - !Ref WorkStationSecurityGroup
      Tags:
      - Key: Name
        Value: "WorkStationServer-EKS"
      - Key: !Sub 'kubernetes.io/cluster/${EKSMaster}'
        Value: 'owned'
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: "20"
            VolumeType: gp2
            DeleteOnTermination: true
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -x
            HOME=/home/ec2-user

            #Writes logging of my userdata to /var/log/user-data.log file
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

            # Install kubectl
            curl -o kubectl ${KubectlBinarylink}
            chmod +x kubectl && mv kubectl /usr/local/bin/
            echo 'export PATH=/usr/local/bin/:$PATH' >> $HOME/.bashrc

            # Install aws-iam-authenticator
            curl -o aws-iam-authenticator ${AwsIamAuthenticatorBinaryLink}
            chmod +x ./aws-iam-authenticator && mv aws-iam-authenticator /usr/local/bin/
            echo 'export PATH=/usr/local/bin/:$PATH' >> $HOME/.bashrc

            #Configure kubectl
            mkdir $HOME/.kube 
            aws eks update-kubeconfig --name ${EKSMaster} --role-arn ${CFNServiceRoleArn} --region ${AWS::Region} && chown ec2-user:ec2-user /root/.kube/* && mv /root/.kube/config /root/.kube/config-${EKSMaster} && mv /root/.kube/config-${EKSMaster} /home/ec2-user/.kube/
            echo 'export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config-${EKSMaster}' >> $HOME/.bashrc
            chown -R ec2-user:ec2-user $HOME/.kube
            source $HOME/.bashrc

            #TrustRelationship logic between WorkStationInstance and CFNServiceRole
            cat <<EOF > $HOME/Role-Trust-Policy.json
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "cloudformation.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
                },
                {
                    "Effect": "Allow",
                    "Principal": {
                        "AWS": [
                          "${WorkStationInstanceRole.Arn}"
                        ]
                    },
                    "Action": "sts:AssumeRole"
                }
              ]
            }
            EOF

            #Set trust between WorkStationInstance and CFNServiceRole
            aws iam update-assume-role-policy --role-name ${CFNServiceRole} --policy-document file://$HOME/Role-Trust-Policy.json
            
            #Configure ConfigMap for attaching Worker nodes
            curl -o $HOME/.kube/aws-auth-cm.yaml https://raw.githubusercontent.com/aws-samples/eks-refarch-cloudformation/master/configuration/aws-auth-cm.yaml
            sed -i -e "s#<ARN of instance role (not instance profile)>#${NodeInstanceRoleArn}#g" $HOME/.kube/aws-auth-cm.yaml

            #Configure ConfigMap with an ExtraInstanceRole which we will use it later for achieving security.
            sed -i -e "s#<ARN of additional instance role>#${ExtraInstanceRole.Arn}#g" $HOME/.kube/aws-auth-cm.yaml
            sleep 0.5m
            kubectl apply -f $HOME/.kube/aws-auth-cm.yaml

            #For achieving security, detach the TrustRelationship between WorkStation EC2 Instance and RBAC Role.
            cat <<EOF > $HOME/UnSetRole-Trust-Policy.json
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "cloudformation.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
                }
              ]
            }
            EOF
            aws iam update-assume-role-policy --role-name ${CFNServiceRole} --policy-document file://$HOME/UnSetRole-Trust-Policy.json

            #Setting the ExtraInstanceRole in Kubectl configmap
            sed -i -e "s#${CFNServiceRoleArn}#${ExtraInstanceRole.Arn}#g" $HOME/.kube/config-${EKSMaster}

            #Creating "view" level permissions for accessing Kubernetes Dashboard
            curl -o $HOME/eks-view-service-account.yaml https://raw.githubusercontent.com/aws-samples/eks-refarch-cloudformation/master/configuration/k8sdashboard-view.yaml
            kubectl apply -f $HOME/eks-view-service-account.yaml

            #Deploy Official Kubernetes dashboard. If the below link gets outdated, refer to "https://github.com/kubernetes/dashboard" for working link.
            kubectl apply -f ${k8sDashboardlink}
            until kubectl get pods -n kube-system -l k8s-app=kubernetes-dashboard | grep 1/1; do sleep 1; done
            
            #Deploy Heapster and Influxdb backend for heapster cluster
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml

      
Outputs:
  WorkStation:
    Description: The Worker nodes instance IAM role
    Value: !GetAtt WorkStation.PublicIp